! This file is part of kettera - a numerical solver and visualizer for 
! the time-dependent Schrödinger equation
! Copyright (C) 2026 Juuso Kaarela
! 
! Kettera is free software: you can redistribute it and/or modify it under the terms of
! the GNU General Public License as published by the Free Software Foundation, either
! version 3 of the License, or (at your option) any later version.
!
! Kettera is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
! without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
! See the GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License along with kettera.
! If not, see <https://www.gnu.org/licenses/>.

module io_parameters
  use kinds

  implicit none

  ! ----- Numerical parameters -----
  integer(label), parameter, public :: MAX_STR_LEN = 200_label
  integer(label), parameter, public :: PARAM_FILE_UNIT = 10_label
  integer(label), parameter, public :: INPUT_FILE_UNIT = 20_label
  integer(label), parameter, public :: OUTPUT_FILE_UNIT = 30_label
  integer(label), parameter, public :: LOG_FILE_UNIT = 40_label

  ! ----- String parameters -----

  ! Simple format strings
  character(*), parameter, public :: SINGLE_DIGIT_DOUBLE_FMT = 'F17.15'
  character(*), parameter, public :: SINGLE_FMT = 'ES13.6E2'
  character(*), parameter, public :: DOUBLE_FMT = 'ES23.15E3'
  character(*), parameter, public :: EXTENDED_FMT = 'ES27.18E4'
  character(*), parameter, public :: QUADRUPLE_FMT = 'ES42.33E4'
  character(*), parameter, public :: COMPLEX_FMT = '('//DOUBLE_FMT//',SP,'//DOUBLE_FMT//',"*i")'

  ! Default file names
  character(len=MAX_STR_LEN), parameter, public :: DEFAULT_PARAM_FILE = 'params.in'
  character(len=MAX_STR_LEN), parameter, public :: DEFAULT_INPUT_FILE = 'wave.in'
  character(len=MAX_STR_LEN), parameter, public :: DEFAULT_OUTPUT_FILE = 'wave.out'
  character(len=MAX_STR_LEN), parameter, public :: DEFAULT_LOG_FILE = 'ket.out'

  ! Output file strings and format strings
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_TITLE_1 = &
    '# This file was generated by kettera and contains the output data from a simulation'
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_TITLE_2 = &
    '# as frames that represent the state of the system at a given time. The frames can be'
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_TITLE_3 = &
    "# animated or a single frame plotted using the program 'ketanim' supplied with kettera"
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_HEADER_FMT = '("Framecount=",I0,";Method=",I0,";X-Bound=",F0.2,";PotType=",I0,";ImagTime=",I0)'
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_DATA_FIELDS = 'X-coord;Amplitude;Real;Imag;Probability;Potential'
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_FRAME_FMT = '("Frame=",I0)'
  character(len=MAX_STR_LEN), parameter, public :: OUTPUT_DATA_FMT = '(5('//DOUBLE_FMT//',";"),'//DOUBLE_FMT//')'

  ! Log file strings and format strings
  character(len=MAX_STR_LEN), parameter, public :: LOG_TITLE_1 = &
    '# This file was generated by kettera and contains the parameters used to run a simulation'
  character(len=MAX_STR_LEN), parameter, public :: LOG_TITLE_2 = &
    '# as well as the calculated physical quantities for each time step. The quantities can be'
  character(len=MAX_STR_LEN), parameter, public :: LOG_TITLE_3 = &
    "# plotted using the program 'ketplot' supplied with kettera"
  character(len=MAX_STR_LEN), parameter, public :: LOG_FILES_TITLE = '# FILES USED/GENERATED:'
  character(len=MAX_STR_LEN), parameter, public :: LOG_PARAMS_TITLE = '# SIMULATION PARAMETERS USED/GENERATED:'
  character(len=MAX_STR_LEN), parameter, public :: LOG_RESULTS_TITLE = '# SIMULATION RESULTS:'
  character(len=MAX_STR_LEN), parameter, public :: LOG_QUANTITIES_TITLE = '# CALCULATED PHYSICAL QUANTITIES:'
  character(len=MAX_STR_LEN), parameter, public :: LOG_HEADER_FMT = '("Framecount=",I0,";Method=",I0,";PotType=",I0,";ImagTime=",I0)'
  character(len=MAX_STR_LEN), parameter, public :: LOG_DATA_FIELDS = 'TimeStep;Energy;NormSquared'
  character(len=MAX_STR_LEN), parameter, public :: LOG_DATA_FMT = '(I8,";",'//DOUBLE_FMT//',";",'//DOUBLE_FMT//')'


end module io_parameters
